### ISSUE TITLE
在特定情况下反复触发邮件提醒

### ISSUE THREAD

**Issue by TonyWu-21474** [10086mea/nimisora-homowork-notify#1]
RT，在特定条件（未确定）下，会发送意料外的大量邮件
![Uploading 微信图片_20241204013556.png…]()

**Comment by TonyWu-21474** [comment]
具体来说是大约每23分钟重复发送一次邮件

**Comment by 10086mea** [comment]
上传的图片无法预览，可否提供可查看的图片？实现逻辑是每隔15min爬取一次最新作业，和本地储存的csv文件进行对比，是不是csv文件被excel打开后占用了读写权限？

**Comment by 10086mea** [comment]
破案了，2024计算机原理与接口第四次实验报告 这个被布置了两次，两次作业的标题相同截止时间不同，我没使用作业ID作为索引，因此作业标题的冲突就会导致这个问题

**Comment by 10086mea** [comment]
确认了，还不止是这个问题，你两次订阅设置的阈值不一样，我缓存的用户信息只保存了阈值类型，没料到会有人订阅两次而且两次阈值不同，正好今天有个作业卡在了48小时和72小时之间，导致每次检测的时候作业类型都会发生变化

**Comment by cantixe** [comment]
你是这个
